# Generated by Django 4.2.15 on 2024-08-29 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='food_product',
            field=models.BooleanField(default=False),
        ),
    ]
